### ISSUE TITLE
Node_modules no repositório

### ISSUE THREAD

**Issue by NKKFu** [vinniciusgomes/realtime-chat#1]
Queria avisá-lo que este repositório está com o "node_modules" dentro do repositório do github que aliás, não possui um .gitignore. 

também tenho um projetinho parecido com esse no meu git, se quiser, dá uma passada lá 😅
https://github.com/NKKFu/realtime-chat

**Comment by vinniciusgomes** [comment]
Valeu @NKKFu, corrigido!!
